Add unit test and reporting to workflow

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -36,7 +36,13 @@ jobs:
         run: echo "dateAndTime=$(date +'%Y-%m-%d-%H:%M')" >> $GITHUB_OUTPUT
       - name: Install PlatformIO Core
         run: pip install --upgrade platformio
-
+      - name: Run unit tests
+        run: mkdir -p junit-reports && pio test -e native_test_only --junit-output-path --junit-output-path junit-reports/
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/junit-reports/*.xml'
       - name: Build BTClock firmware
         run: pio run -e lolin_s3_mini_qr 
 
